#pragma once

#define CIHB_MAX_DATA_SIZE		1350

typedef enum {
	CIHB_HEARTBEAT_REQUEST,
	CIHB_HEARTBEAT_RESPONSE
} CiHBMessageType_t;

typedef enum {
	CIHB_STATE_ALIVE,
	CIHB_STATE_SW_ERROR,
	CIHB_STATE_HW_ERROR
} CiHBState_t;
