#pragma once

#define CIHB_MAX_DATA_SIZE		1350

typedef enum {
	CIHB_HEARTBEAT_REQUEST,
	CIHB_HEARTBEAT_RESPONSE
} CiHBMessageType_t;

typedef enum {
	CIHB_STATE_ALIVE,
	CIHB_STATE_SW_ERROR,
	CIHB_STATE_HW_ERROR
} CiHBState_t;

typedef enum {
	CIHB_REQUEST_STATE_INIT = 0,
	CIHB_REQUEST_STATE_REQUESTED,
	CIHB_REQUEST_STATE_RESPONSED_ALIVE,
	CIHB_REQUEST_STATE_RESPONSED_MY_SW_ERROR,
	CIHB_REQUEST_STATE_RESPONSED_MY_HW_ERROR
} CCiHBRequestState_t;
